### ISSUE TITLE
Introduce action concurrency

### ISSUE THREAD

**Issue by millnut** [localgovdrupal/github_workflow_manager#10]
When working on https://github.com/localgovdrupal/localgov_project/pull/131 I noticed each commit to the PR started a new github action workflow (https://github.com/localgovdrupal/localgov_project/actions?query=branch%3Afeature%2F3.x%2Ffix-phpstan-checks++)

We could make a significant saving on the amount of CI/CD minutes used by running concurrency and cancelling any in-progress workflows for the same branch and only running the latest.

Something like;
```yaml
on:
  push:
    branches:
      - '3.x'
  pull_request:
    branches:
      - '3.x'
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true
```

More info [here](https://docs.github.com/en/actions/using-jobs/using-concurrency) and to start a discussion as not sure how many minutes are used per month currently.

cc: @finnlewis
